// //### First generated by SKot but then you can (have to) edit, the main constructor only will modifyed by generator if needed
package tech.skot.demo.screens

import kotlin.String

class SplashViewImpl(
  messageInitial: String,
  title: String
) : SplashViewImplGen(messageInitial, title) {
  override fun onMessage(message: String) {
    TODO("SK: generated and not implemented")
  }

  override fun onTitle(title: String) {
    TODO("SK: generated and not implemented")
  }
}
