// //### First generated by SKot but then you can (have to) edit, the main constructor only will modifyed by generator if needed
package tech.skot.demo.screens

import tech.skot.view.extensions.setVisible

class SplashViewImpl(
  messageInitial: String
) : SplashViewImplGen(messageInitial) {
  override fun onMessage(message: String) {
    binding.tvMessage.text = message
  }


  override fun onLoading(loading: Boolean) {
    binding.progressBar.root.setVisible(loading)
  }
}
