// //### First generated by SKot but then you can (have to) edit, the main constructor only will modifyed by generator if needed
package tech.skot.demo.screens

import tech.skot.view.extensions.setOnClick
import tech.skot.view.extensions.setVisible
import kotlin.String

class SplashViewImpl(
  messageInitial: String,
  onTapButton: Function0<Unit>,
  onTapButton2: Function0<Unit>,
  title: String
) : SplashViewImplGen(messageInitial, onTapButton, onTapButton2, title) {
  override fun onMessage(message: String) {
    binding.tvMessage.text = message
  }

  override fun onTitle(title: String) {
    binding.tvTitle.text = title
  }

  override fun onOnTapButton(onTapButton: () -> Unit) {
    binding.button.setOnClick(onTapButton)
  }

  override fun onOnTapButton2(onTapButton2: () -> Unit) {
    binding.button2.setOnClick(onTapButton2)
  }
  override fun onLoading(loading: Boolean) {
    binding.progressBar.root.setVisible(loading)
  }
}
