// //### First generated by SKot but then you can (have to) edit, the main constructor only will modifyed by generator if needed
package tech.skot.demo.screens

import tech.skot.view.extensions.setOnClick
import tech.skot.view.extensions.setVisible
import kotlin.Function0
import kotlin.Unit

class WithBackScreenViewImpl(
  onTapBack: Function0<Unit>,
  onTapOpen: Function0<Unit>
) : WithBackScreenViewImplGen(onTapBack, onTapOpen) {

  override fun setPaddingTopStatusBar() = true

  override fun onOnTapBack(onTapBack: Function0<Unit>) {
    binding.btnBack.setOnClick(onTapBack)
  }

  override fun onOnTapOpen(onTapOpen: () -> Unit) {
    binding.btnOpen.setOnClick(onTapOpen)
  }

  override fun onLoading(loading: Boolean) {
    binding.progressBar.root.setVisible(loading)
  }
}
